apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-trace
spec:
  mode: deployment

  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
      # jaeger:
      #   protocols:
      #     thrift_compact:
      #       endpoint: 0.0.0.0:6831

    exporters:
      otlp/jaeger:
        endpoint: jaeger-collector.observability:4317
        tls:
          insecure: true

    service:
      telemetry:
        logs:
          level: "debug"
      pipelines:
        traces:
          receivers:
            - otlp
            # - jaeger
          exporters:
            - otlp/jaeger

  # config: |
  #   receivers:
  #     otlp:
  #       protocols:
  #         grpc:
  #           endpoint: 0.0.0.0:4317
  #     jaeger:
  #       protocols:
  #         thrift_compact:
  #           endpoint: 0.0.0.0:6831

  #   exporters:
  #     jaeger:
  #       endpoint: jaeger-collector.observability:14250
  #       tls:
  #         insecure: true

  #   service:
  #     telemetry:
  #       logs:
  #         level: "debug"
  #     pipelines:
  #       traces:
  #         receivers:
  #           - otlp
  #           - jaeger
  #         exporters:
  #           - jaeger
